name: Node.js 서버 자동 배포

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v2
      - name: Node.js 설치
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: 패키지 설치
        run: npm install
      - name: 서버 실행
        run: npm start
