name: develop

on:
  push:
    branches: [develop]

jobs:
  CI_CD:
    name: CI/CD
    runs-on: [self-hosted, 'PinTalk runner']
    steps:
      - name: Deploy
        run: |
          cd ~/PinTalk-Front
          git fetch --all && git reset --hard origin/develop && git pull origin develop
          npm install
          npm run build   
          kill $(lsof -t -i:3000)
          nohup npm run start & 
