name: develop

on:
  push:
    branches: [develop]

jobs:
  KILL:
      name: Kill
      runs-on: [self-hosted, 'PinTalk runner']
      steps:
        - name: Kill
          run: |
            kill $(lsof -t -i:3000) || echo 'No previous process'
  CI_CD:
    name: CI/CD
    runs-on: [self-hosted, 'PinTalk runner']
    needs: KILL
    steps:
      - name: Deploy
        run: |
          cd ~/PinTalk-Front
          git fetch --all && git reset --hard origin/develop && git pull origin develop
          npm install
          npm run build
          screen -d -m npm run start
